import test from 'node:test';
import assert from 'node:assert/strict';
import {handleRequest,schedule,processJob} from '../src/worker.ts';
import {Store} from '../src/store.ts';
import {testDatabase} from './sqlite.ts';
import type {Env,QueueJob} from '../src/types.ts';
const game={id:'018d937f-07fc-72ed-8517-d8e24cb1eb22',slug:'game',title:'Game',type:'game'};
function setup(enabled='true'){const t=testDatabase();const jobs:QueueJob[]=[];const env={DB:t.db,WORK_QUEUE:{send:async(body:QueueJob)=>{jobs.push(body)},sendBatch:async(items:any[])=>{jobs.push(...items.map(i=>i.body))}},TELEGRAM_BOT_TOKEN:'test',TELEGRAM_WEBHOOK_SECRET:'secret',ITAD_API_KEY:'test',SCANS_ENABLED:enabled,TELEGRAM_CHAT_ID:'1'} as unknown as Env;return {...t,env,jobs,store:new Store(t.db)}}
const hook=(body:unknown,secret='secret')=>new Request('https://bot.test/telegram',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':secret,'Content-Type':'application/json'},body:JSON.stringify(body)});
test('webhook authenticates, persists before ack, and deduplicates replay',async()=>{const t=setup();try{assert.equal((await handleRequest(hook({update_id:1},'wrong'),t.env,1000)).status,403);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM telegram_updates').get()!.n,0);assert.equal((await handleRequest(hook({update_id:1}),t.env,1000)).status,200);await handleRequest(hook({update_id:1}),t.env,1001);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM telegram_updates').get()!.n,1);assert.equal(t.jobs[0].kind,'update')}finally{t.close()}});
test('queue failure preserves webhook for durable recovery',async()=>{const t=setup();try{t.env.WORK_QUEUE.send=async()=>{throw new Error('queue down')};assert.equal((await handleRequest(hook({update_id:2}),t.env,1000)).status,503);assert.deepEqual(await t.store.pendingUpdates(1000),[2]);}finally{t.close()}});
test('paused scans do nothing; enabled cron creates bounded durable jobs without overlap',async()=>{const t=setup('false');try{await schedule(t.env,1000);assert.equal(t.jobs.length,0);await t.store.addWishlist('1',null,game,null,1000);t.env.SCANS_ENABLED='true';await schedule(t.env,2000);assert.equal(t.jobs.filter(j=>j.kind==='scan').length,2);await schedule(t.env,2001);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM scan_runs').get()!.n,2)}finally{t.close()}});
test('delivery429 retains reference and retry timing, then records confirmed send',async()=>{const t=setup();try{await t.store.queueMessage('reply:1','1','Hello');let n=0;const fetcher=async()=>{n++;return new Response(JSON.stringify(n===1?{ok:false,error_code:429,parameters:{retry_after:60}}:{ok:true,result:{}}),{status:n===1?429:200})};const now=Date.now();assert.equal(await processJob({kind:'delivery',id:'reply:1'},t.env,now,fetcher as typeof fetch),60);assert.equal(t.sqlite.prepare('SELECT status FROM deliveries').get()!.status,'pending');await processJob({kind:'delivery',id:'reply:1'},t.env,now+60001,fetcher as typeof fetch);assert.equal(t.sqlite.prepare('SELECT status FROM deliveries').get()!.status,'sent')}finally{t.close()}});
test('delivery403 quarantines recipient; paused market alerts are not sent',async()=>{const t=setup();try{await t.store.queueMessage('reply:1','1','Hello');await processJob({kind:'delivery',id:'reply:1'},t.env,Date.now(),(async()=>new Response(JSON.stringify({ok:false,error_code:403}),{status:403})) as typeof fetch);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM blocked_chats').get()!.n,1)}finally{t.close()}});
test('complete quiet price scan refreshes imported baseline without notifications',async()=>{const t=setup();try{await t.store.addWishlist('1',null,game,{gameId:game.id,shop:'GOG',shopId:35,url:'https://gog.com/game/g',priceCents:10000,regularCents:10000,cut:0,currency:'EUR',expiry:null},1000);await schedule(t.env,2000);const job=t.jobs.find(j=>j.kind==='scan'&&t.sqlite.prepare('SELECT payload FROM scan_jobs WHERE id=?').get(j.id)!.payload!.toString().includes('prices'))!;await processJob(job,t.env,2001,(async()=>new Response(JSON.stringify([{id:game.id,deals:[{shop:{id:35,name:'GOG'},url:'https://gog.com/game/g',price:{amountInt:2000,currency:'EUR'},regular:{amountInt:10000,currency:'EUR'},cut:80,expiry:null}]}]))) as typeof fetch);assert.equal((await t.store.getWishlist('1'))[0].baseline_price_cents,2000);assert.equal((await t.store.pendingDeliveries(2001)).length,0);assert.equal(await t.store.getSetting('prices_seeded'),'true')}finally{t.close()}});

test('admin trigger only enqueues small scheduler parts and leaves database work to consumers',async()=>{const t=setup();try{const request=new Request('https://bot.test/admin/scan',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'secret'}});assert.equal((await handleRequest(request,t.env,2000)).status,200);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM scan_runs').get()!.n,0);assert.deepEqual(t.jobs.map(j=>j.kind),['tick','tick','tick']);for(const job of t.jobs.slice())await processJob(job,t.env,2001);assert.equal(t.sqlite.prepare('SELECT COUNT(*) n FROM scan_runs').get()!.n,2)}finally{t.close()}});

test('scheduler parts can arrive in any order and still publish scan work',async()=>{const t=setup();try{for(const part of ['recover','giveaways','prices'] as const)await processJob({kind:'tick',part,scheduledAt:2000,initialize:false},t.env,2001);assert.ok(t.jobs.some(j=>j.kind==='scan'));}finally{t.close()}});

test('failed scan publication releases dispatch marker for prompt retry',async()=>{const t=setup();try{await t.store.addWishlist('1',null,game,null,1000);const send=t.env.WORK_QUEUE.sendBatch;t.env.WORK_QUEUE.sendBatch=async()=>{throw Error('publish failed')};await assert.rejects(()=>processJob({kind:'tick',part:'prices',scheduledAt:2000,initialize:false},t.env,2000));assert.equal(t.sqlite.prepare('SELECT enqueued_at FROM scan_jobs').get()!.enqueued_at,null);t.env.WORK_QUEUE.sendBatch=send;await processJob({kind:'tick',part:'prices',scheduledAt:2000,initialize:false},t.env,62001);assert.ok(t.jobs.some(j=>j.kind==='scan'));}finally{t.close()}});
